FROM node:20.9.0-bookworm

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

ENV PSWD_DECRYPT_CODE="likoson"
ENV STRIPE_KEY="sk_test_51OCBE7IJLm2DQzDdB4eAcQFC5DH2ffavB9meM8OSl44THDK68bHr8qz0xXKeOEOmBtcrmLOrtHFq1mXuppsLFUZp00G99phDsw"
ENV CLIENT_ID_GOOGLE="689024350629-j6e7j8q5qg11r96bdaqtjp4ln2ut7bjr.apps.googleusercontent.com"
ENV CLIENT_SECRET_GOOGLE="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"
ENV TOKEN_GOOGLE="1//04Uo9r__72JIuCgYIARAAGAQSNwF-L9Ir6cK9qnkk0VPg8rnYXXwQ4HJnzsaoPZhE3AbDsRMWbgSvfW8LuQNs6GGwAxhPyJIfQpM"
ENV DATA_BASE="TheLikoTest"
COPY package.json ./ 

RUN npm install

COPY . . 

ENTRYPOINT npm run start.dev