name: Deploy to Azure

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push Docker image'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: the-liko-resources.azurecr.io/api_rest_image:latest

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apitheliko'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'the-liko-resources.azurecr.io/api_rest_image:latest'
